AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Opportunity Tracker Lambda

Resources:
  OpportunityTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 256
      Timeout: 300
      Environment:
        Variables:
          S3_BUCKET: <BUCKET_NAME>
          TWILIO_ACCOUNT_SID: <ACCOUNT_SID>
          TWILIO_AUTH_TOKEN: <AUTH_TOKEN>
          TWILIO_PHONE_NUMBER: <TWILIO_NUMBER>
          MY_PHONE_NUMBER: <PHONE_NUMBER>
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: arn:aws:s3:::<BUCKET_NAME>/*
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day) 
